### ISSUE TITLE
Refresh on 8000

### ISSUE THREAD

**Issue by jbathel** [jbathel/little-foot-trails#35]
When you are viewing app on localhost:8000 and go to a detail page for a trail, if you refresh it throughs a 404 error. This doesn't not happen on localhost:3000

**Comment by rmiyazaki6499** [comment]
@jbathel Have you tried running npm run build? Usually when something works on 3000 but not 8000 would be because the production build has not been run

**Comment by jbathel** [comment]
Ran npm build, master is totally up to date. Also, getting broken image on the detail page now.

**Comment by rmiyazaki6499** [comment]
@jbathel , please create a new issue with regards to the image breaking and assign it to @banuaksom as I'm pretty sure that it is separate from the 404 issue.
